# Use an official lightweight Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script
COPY app.py .

# Command to run the app
CMD ["python", "app.py"]
