name: CI Pipeline with Bandit and Docker Scout

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install Bandit for security analysis
      - name: Install Bandit
        run: |
          pip install bandit

      # Step 4: Run Bandit to check for security issues in the Python code
      - name: Run Bandit Security Analysis
        run: bandit -r app.py

      # Step 5: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t python-hello-world .

      # Step 6: Install Docker CLI
      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      # Step 7: Install Docker Scout (via Docker CLI)
      - name: Install Docker Scout via Docker CLI
        run: |
          docker plugin install docker-scout

      # Step 8: Run Docker Scout to scan the image for security vulnerabilities
      - name: Scan Docker Image with Docker Scout
        run: |
          docker scout image python-hello-world

      # Step 9: Clean up
      - name: Clean up Docker containers
        run: docker system prune -f
