name: Security Scans

on: [push, pull_request]

jobs:
  security_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Install Bandit for Python security analysis
      - name: Install Bandit
        run: pip install bandit

      # ✅ Run Bandit Scan
      - name: Run Bandit Security Scan
        run: bandit -r .

      # ✅ Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose
          sudo systemctl enable docker
          sudo systemctl start docker

      # ✅ Install Docker Scout
      - name: Install Docker Scout CLI
        run: |
          curl -fsSL https://download.docker.com/linux/static/stable/amd64/docker-20.10.7.tgz | tar xzvf - --strip-components=1 -C /usr/local/bin
          docker --version
          docker scout --version

      # ✅ Build Docker Image
      - name: Build Docker Image
        run: docker build -t my-python-app:latest .

      # ✅ Scan Docker Image using Docker Scout
      - name: Scan Docker Image with Docker Scout
        run: docker scout cves my-python-app:latest
